---
title: "Assignments"
subtitle: "Spring 2025"
format: 
  html:
    page-layout: full
    theme: cosmo
    toc: true
    toc-title: "Contents"
    embed-resources: true
    standalone: true
editor: 
  markdown: 
    wrap: 72
---

All homework, essays, labs, and project files can be accessed through
the [Google
Drive](https://drive.google.com/drive/folders/1-2MqxLJzUI0wxI8IhVN17Et8YvWTRxF-?usp=sharing).
Please note that you must have a Vassar email in order to access the
folder.

## **Ungraded Assignments to Prepare for Class**

**01/23/25.** Install Python, R, and RStudio on your personal computer.
See the syllabus for links to installation instructions. Additionally,
look over the R vs. Python slides (in the folder Notes \> 1-R-vs-Python)
before class on Tuesday.

**01/28/25.** Install Git and make a Github account. See the syllabus
for instructions.

**01/30/25.** Look over the slides in Notes \> 3-R-Python-datasci before
class on Tuesday. Additionally, fill out the course check-in by Monday.
The form link is posted in Slack in `#m244-announcements`

**02/06/25**. Look over the slides in Notes \> 5-datavis-R before class
on Tuesday. Additionally, fill out the course check-in by Monday.

**02/11/25.** Look over the slides in Notes \> 6-datavis-py before class
on Thursday.

**02/13/25.** Look over the slides in Notes \> 7-webscraping-R before
class on Tuesday. Additionally, fill out the course check-in by Monday.

## Homework

All homework assignments will be submitted to Gradescope.

0.  Course Information sheet. This is due Thursday, January 30th.
1.  Data Science in R and Python. This is due Thursday, February 13th.

## Essays

1.  *My Coding Autobiography.* This is open ended and some things you
    can include are:\
    \* When did you start coding and why?\
    \* How do you learn coding?\
    \* What have been your biggest successes and struggles with coding?\
    \* What are your coding goals?\
    This is due Tuesday, February 4th in Gradescope.

2.  *Data Visualization.* Read the two articles on misleading data
    visualizations during COVID-19 in the Essays \> 2-data-vis folder.
    In your essay, include the following:\
    \* Summarize the main take-aways in the two articles.\
    \* Comment on both good or bad data visualizations you have
    encountered.\
    \* What will be your general approach for approaching data
    visualizations in the future?\
    Your essay should be around 1-2 pages in length. This is due
    Thursday, February 20th in Gradescope.

## Labs

1.  *Introduction to Git for Version Control.* 01/30. We will finish it
    in class on Tuesday, February 4th.
2.  *R, Python, and Git: Oh My!* 02/06. This is due Monday, February
    10th in Gradescope.
3.  *Data Visualization in R and Python*. 02/11 and 02/13. This is due
    Monday, February 17th in Gradescope.

## Project

TBA
